if(NOT DEFINED BOOTGEN OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED OUTPUT_DIR OR NOT DEFINED ARCH OR NOT DEFINED EXPECTED_READ_OUTPUT)
    message(FATAL_ERROR "BOOTGEN, FIXTURE_DIR, OUTPUT_DIR, ARCH, and EXPECTED_READ_OUTPUT are required")
endif()

file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(TEST_FIXTURE_DIR "${OUTPUT_DIR}/fixture")
file(MAKE_DIRECTORY "${TEST_FIXTURE_DIR}")
file(COPY "${FIXTURE_DIR}/versal-smoke.bif" "${FIXTURE_DIR}/zynq-smoke.elf" DESTINATION "${TEST_FIXTURE_DIR}")
set(BOOT_IMAGE "${OUTPUT_DIR}/BOOT.BIN")

execute_process(
    COMMAND "${BOOTGEN}" -arch "${ARCH}" -image "${TEST_FIXTURE_DIR}/versal-smoke.bif" -o "${BOOT_IMAGE}" -w on
    WORKING_DIRECTORY "${TEST_FIXTURE_DIR}"
    RESULT_VARIABLE CREATE_RESULT
    OUTPUT_VARIABLE CREATE_OUTPUT
    ERROR_VARIABLE CREATE_ERROR)
if(NOT CREATE_RESULT EQUAL 0)
    message(FATAL_ERROR "${ARCH} smoke image creation failed (${CREATE_RESULT}):\n${CREATE_OUTPUT}\n${CREATE_ERROR}")
endif()

file(SIZE "${BOOT_IMAGE}" BOOT_IMAGE_SIZE)
if(BOOT_IMAGE_SIZE LESS 512)
    message(FATAL_ERROR "${ARCH} smoke image is unexpectedly small: ${BOOT_IMAGE_SIZE} bytes")
endif()

execute_process(
    COMMAND "${BOOTGEN}" -arch "${ARCH}" -read "${BOOT_IMAGE}"
    RESULT_VARIABLE READ_RESULT
    OUTPUT_VARIABLE READ_OUTPUT
    ERROR_VARIABLE READ_ERROR)
if(NOT READ_RESULT EQUAL 0)
    message(FATAL_ERROR "${ARCH} smoke image inspection failed (${READ_RESULT}):\n${READ_OUTPUT}\n${READ_ERROR}")
endif()

string(FIND "${READ_OUTPUT}" "${EXPECTED_READ_OUTPUT}" EXPECTED_OUTPUT_OFFSET)
if(EXPECTED_OUTPUT_OFFSET EQUAL -1)
    message(FATAL_ERROR "${ARCH} smoke image metadata does not match the input ELF:\n${READ_OUTPUT}")
endif()
